django_test/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

feedback/urls.py
from django.conf.urls import url

from . import views

app_name='feedback'
urlpatterns = [
	url(r'^$', views.index_view, name='index'),
	url(r'^login/$', views.login_view, name='login'),
	url(r'^logout/$', views.logout_view, name='logout'),
	url(r'^msg/$', views.msg, name='msg'),	
]
	

polls/urls.py
from django.conf.urls import url

from . import views

app_name='polls'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

feedback/models.py
from __future__ import unicode_literals

from django.db import models
from django.forms import ModelForm

# Create your models here.
class Messages(models.Model):
	date = models.DateTimeField(auto_now_add=True)
	sender = models.CharField(max_length=100)
	text = models.TextField(max_length=1000)
	
	def __str__(self):
		return self.sender

polls/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	
	def __str__(self):
		return self.question_text
	
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	
	def __str__(self):
		return self.choice_textq.choice_set.create(choice_text="Not much", votes=0)

feedback/forms.py
from django import forms

class LoginForm(forms.Form):
	username=forms.CharField(label='Login', max_length=100)
	password=forms.CharField(label='Password', widget=forms.PasswordInput, max_length=100)
	
class MsgForm(forms.Form):
	#date=forms.DateTimeField(disabled=True)
	email=forms.EmailField(label='E-mail', max_length=100)
	text=forms.CharField(label='Message', max_length=1000, widget=forms.Textarea)

feedback/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.core.mail import send_mail

# Create your views here.
from .forms import LoginForm, MsgForm
from .models import Messages
def index_view(request):
	if request.user.is_authenticated():
		msg_form=MsgForm()
		return render(request, 'feedback/index.html', {'form':msg_form})

	else:
		return HttpResponseRedirect(reverse('feedback:login'))
	
	
def login_view(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		
		if form.is_valid():			
			user = authenticate(username=request.POST['username'], password=request.POST['password'])
			
			if user is not None:
				
				if user.is_active:
					login(request, user)
					return HttpResponseRedirect(reverse('feedback:index'),{'user': user})
				else:
					return HttpResponse('User is disabled')	
			else:
				return HttpResponse('Invalid login')
		else:
			return HttpResponse('Input data is invalid')	
	else:
		logon_form = LoginForm()
		return render(request, 'feedback/login.html', {'form':logon_form})

def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('feedback:index'))
	

def msg(request):
	if request.method == 'POST':
		if request.user.is_authenticated():
			form=MsgForm(request.POST)
			if form.is_valid():
				
				message=Messages(sender=form.cleaned_data['email'], text = form.cleaned_data['text'])
				#send_mail('Message from user',form.cleaned_data['text'],form.cleaned_data['email'],['root@example.com'], fail_silently=False)
				
				message.save()
				
				return HttpResponse('Message sent')
			else:
				return HttpResponseRedirect(reverse('feedback:index'))
	else:
		return HttpResponseRedirect(reverse('feedback:index'))
		
	return HttpResponse(msg_block)

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question
# Create your views here

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'
	
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
		
class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
 		return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'


def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html',{
			'question':question,
			'error_message': "You didn't select a choice",
		})
	else:
		selected_choice.votes +=1
		selected_choice.save()
	
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
		


# def index(request):
# 	latest_question_list = Question.objects.order_by('-pub_date')[:5]
# 	context = {'latest_question_list':latest_question_list,}
# 	return render(request, 'polls/index.html', context)
# 	
#
# def detail(request, question_id):
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, 'polls/detail.html', {'question':question})
# 	
#
# def results(request, question_id):
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, 'polls/results.html', {'question':question})
#
# 	

feedback/templates/feedback/index.html
Logged in as: {{ user }}
<center>
{{ form.non_field_errors }}
<form action="{% url 'feedback:msg' %}" method="post">
	{% csrf_token %}	
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }}<br>{{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}
	<input type="submit" value="Submit">
</form>
</center>
 

feedback/templates/feedback/login.html
Please log in to continue
<form action="{% url 'feedback:login' %}" method="post">
	{% csrf_token %}
	{{ form.as_ul }}
	<input type="submit" value="Log In">
</form>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>